In [1]:
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs

In [3]:
X, y = make_blobs()

In [4]:
k = 5

In [5]:
kmeans = KMeans(n_clusters=k, random_state=42)
y_pred = kmeans.fit_predict(X)

In [6]:
y_pred

array([4, 2, 1, 4, 2, 0, 0, 2, 3, 1, 4, 4, 1, 0, 4, 0, 4, 2, 1, 1, 4, 4,
       4, 1, 1, 3, 3, 1, 1, 1, 3, 1, 1, 3, 2, 3, 1, 1, 1, 3, 3, 3, 1, 3,
       0, 4, 1, 2, 4, 2, 2, 1, 0, 2, 1, 3, 0, 4, 4, 3, 1, 4, 4, 3, 1, 0,
       3, 0, 0, 2, 3, 1, 2, 1, 0, 2, 1, 2, 1, 3, 3, 0, 1, 4, 3, 0, 1, 0,
       1, 2, 2, 4, 1, 2, 1, 3, 4, 1, 1, 1], dtype=int32)

In [7]:
kmeans.cluster_centers_

array([[ 3.67624643,  5.53659069],
       [ 9.06608486, -9.83811304],
       [-1.61183894, -3.45543162],
       [ 2.03401615,  6.02967256],
       [-2.6658586 , -4.81000377]])

In [8]:
import numpy as np
X_new = np.array([[0,2], [3,2], [-3,3], [-3,2.5]])
kmeans.predict(X_new)

array([3, 0, 3, 2], dtype=int32)